policy_kwargs: {}
baseline: shared
num_augment: 8
augment_fn: dihedral8
first_aug_identity: true
feats: null
num_starts: null
optimizer_kwargs:
  lr: 0.0001
embed_dim: 128
num_slots: 8
metric_variant: B
alpha_metric: 0.0
beta_entropy: 0.0
slot_iters: 3
proj_dim: 64
lambda_init: 1.0
lr_dual: 0.001
batch_size: 512
val_batch_size: null
test_batch_size: null
train_data_size: 100000
val_data_size: 10000
test_data_size: 10000
optimizer: Adam
lr_scheduler: null
lr_scheduler_kwargs:
  milestones:
  - 80
  - 95
  gamma: 0.1
lr_scheduler_interval: epoch
lr_scheduler_monitor: val/reward
generate_default_data: false
shuffle_train_dataloader: false
dataloader_num_workers: 0
data_dir: data/
log_on_step: true
metrics: {}
baseline_kwargs: {}
reward_scale: null
